### ISSUE TITLE
It's impossible to import messages from arbitrary namespaces

### ISSUE THREAD

**Issue by clayrat** [hultqvist/ProtoBuf#33]
I have the following structure of proto schemas:
```
/foo/Bar.proto
/baz/Qux.proto
```
Now I want to define a separate schema that utilizes both:
```
/norf/BarAndQux.proto
```
inside which I have smth like
```
package norf;

import "../foo/Bar.proto";
import "../baz/Qux.proto";

message BarAndQux {
   optional Bar bar = 1;
   optional Qux qux = 2;
}
```

While this compiles ok with Java and Scala generators, this code generator is complaining:
```error CS001: Field type "Bar" not found for field bar in message norf.BarAndQux```

It looks like in https://github.com/hultqvist/ProtoBuf/blob/master/CodeGenerator/Proto/Search.cs the search space is only limited to the enclosing and global namespaces.

**Comment by hultqvist** [comment]
I'm afraid import is not yet implemented, I'll use this issue to track its implementation.

A workaround for now is to pass both .proto paths as arguments to CodeGenerator.exe

When it comes to the search code you mentioned I believe it is correct. But since the files weren't imported the messages could not be found.

**Comment by hultqvist** [comment]
Please help me test it.
